
/******************************************************************************
*
*   FILE
*   ----
*   Mul.c
*
*   History
*   -------
*   2017-05-18   File created
*
*******************************************************************************
*
*   This file is generated by the 'acplt_builder' command
*
******************************************************************************/


#ifndef OV_COMPILE_LIBRARY_demolib
#define OV_COMPILE_LIBRARY_demolib
#endif


#include "demolib.h"
#include "ov_macros.h"


OV_DLLFNCEXPORT void demolib_Mul_typemethod(
	OV_INSTPTR_fb_functionblock	pfb,
	OV_TIME						*pltc
) {
    /*    
    *   local variables
    */
    OV_INSTPTR_demolib_Mul pinst = Ov_StaticPtrCast(demolib_Mul, pfb);

    pinst->v_out = pinst->v_in1 * pinst->v_in2;

    /*
     *   versteckte Variable bearbeiten
     */
    pinst->v_zaehler = (pinst->v_zaehler+1)%10000;	/* Aufruf-Zähler*/

    /*
     *   Endebearbeitung
     */
    return;
}

