
/******************************************************************************
*
*   FILE
*   ----
*   Sinus.c
*
*   History
*   -------
*   2017-05-18   File created
*
*******************************************************************************
*
*   This file is generated by the 'acplt_builder' command
*
******************************************************************************/


#ifndef OV_COMPILE_LIBRARY_demolib
#define OV_COMPILE_LIBRARY_demolib
#endif


#include "demolib.h"
#include "ov_macros.h"
#include <math.h>


OV_DLLFNCEXPORT OV_RESULT demolib_Sinus_periode_set(
    OV_INSTPTR_demolib_Sinus          pobj,
    const OV_INT  value
) {
    if(value < 2)
        return OV_ERR_BADVALUE;

    pobj->v_count = 0;
    pobj->v_periode = value;
    return OV_ERR_OK;
}

OV_DLLFNCEXPORT OV_RESULT demolib_Sinus_amplitude_set(
    OV_INSTPTR_demolib_Sinus          pobj,
    const OV_SINGLE  value
) {
	pobj->v_count = 0;
	pobj->v_amplitude = value;

    return OV_ERR_OK;
}

OV_DLLFNCEXPORT OV_RESULT demolib_Sinus_offset_set(
    OV_INSTPTR_demolib_Sinus          pobj,
    const OV_SINGLE  value
) {
	pobj->v_count = 0;
	pobj->v_offset = value;

    return OV_ERR_OK;
}

OV_DLLFNCEXPORT OV_RESULT demolib_Sinus_constructor(
	OV_INSTPTR_ov_object 	pobj
) {
    /*    
    *   local variables
    */
    OV_INSTPTR_demolib_Sinus pinst = Ov_StaticPtrCast(demolib_Sinus, pobj);
    OV_RESULT    result;

    /* do what the base class does first */
    result = fb_functionblock_constructor(pobj);
    if(Ov_Fail(result))
         return result;

    /* do what */
    pinst->v_periode = 2;

    return OV_ERR_OK;  /* Return immer OV_ERR_OK ! */
}

OV_DLLFNCEXPORT OV_RESULT demolib_Sinus_checkinit(
	OV_INSTPTR_ov_object 	pobj
) {
    /*    
    *   local variables
    */
    OV_INSTPTR_demolib_Sinus pinst = Ov_StaticPtrCast(demolib_Sinus, pobj);
    OV_RESULT    result;

    /* do what the base class does first */
    result = fb_functionblock_checkinit(pobj);
    if(Ov_Fail(result))
         return result;

    /* do what */
    if(pinst->v_periode <= 1) {
    	pinst->v_periode = 2;
        // oder return OV_ERR_BADPARAM;
    }

    return OV_ERR_OK;
}

OV_DLLFNCEXPORT void demolib_Sinus_typemethod(
	OV_INSTPTR_fb_functionblock	pfb,
	OV_TIME						*pltc
) {
    /*    
    *   local variables
    */
    OV_INSTPTR_demolib_Sinus pinst = Ov_StaticPtrCast(demolib_Sinus, pfb);

    OV_SINGLE    ZweiPi = 6.283185;

    pinst->v_outD = (OV_DOUBLE)pinst->v_amplitude * sin(ZweiPi * pinst->v_count / pinst->v_periode) + pinst->v_offset;
    pinst->v_outS = (OV_SINGLE)pinst->v_outD;

    pinst->v_count += 1;

    if(pinst->v_count == pinst->v_periode) {
    	pinst->v_count = 0;
    }

    return;
}

